### ISSUE TITLE
TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by Sujeet1604** [bitsensor/elastalert#10]
With a fresh installation and setup below error is poping up. Any guess what is the issue with typescript or configuration

```
15:12:11.344Z ERROR elastalert-server:
    Server:  Starting server failed with error: TypeError: object must be passed
        at module.exports (/home/development/elastalert_server/elastalert/node_modules/object-resolve-path/object-resolve-path.js:13:11)
        at ServerConfig.get (/home/development/elastalert_server/elastalert/src/common/config/server_config.js:32:12)
        at /home/development/elastalert_server/elastalert/src/elastalert_server.js:64:58
        at /home/development/elastalert_server/elastalert/src/common/config/server_config.js:60:9
        at Array.forEach (native)
        at /home/development/elastalert_server/elastalert/src/common/config/server_config.js:59:22
15:12:11.345Z  INFO elastalert-server: Server:  Stopping server
15:12:11.347Z  INFO elastalert-server: Server:  Stopping server
/home/development/elastalert_server/elastalert/src/elastalert_server.js:119
      this._processController.stop();
                             ^

TypeError: Cannot read property 'stop' of null
    at ElastalertServer.stop (/home/development/elastalert_server/elastalert/src/elastalert_server.js:88:5)
    at process.<anonymous> (/home/development/elastalert_server/elastalert/src/elastalert_server.js:30:12)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)

```

**Comment by RubieV** [comment]
Please ensure you have the correct mounts, closing this issue now.
