### ISSUE TITLE
Elastalert enhancemet

### ISSUE THREAD

**Issue by ep4sh** [bitsensor/elastalert#100]
I have rule:
```
---
name: Low number of authentications
alert_text: "Might be some issue - number of successful authentications is too low"
type: flatline
index: "applicationlog-*"
threshold: 1
timeframe:
  hours: 1

filter:
  - query:
      query_string:
        query: 'application:authservice AND (message:"AD authentication succeeded" OR message:"has 0 login attempts, sourceSystem: aServices")'

alert:
  - "email"

email:
  - "my@email.com"

realert:
  days: 1

use_count_query: true

doc_type: applicationLog

match_enhancements:
  - "elastalert_modules.my_enchancement.MyEnhancement"
```

I created enhancement for the rule:
```
from elastalert.enhancements import BaseEnhancement, DropMatchException

class WileyEnhancement(BaseEnhancement):
  def process(self, match):
    if datetime.datetime.now().weekday() in [5, 6]: 
      raise DropMatchException
```

When I click on "TEST RULE" I get an error:
```

Successfully loaded Low number of authentications Would have written the following documents to writeback index (default is elastalert_status): silence - {'rule_name': u'Low number of authentications.all', 
'@timestamp': datetime.datetime(2019, 6, 13, 9, 9, 13, 924147, tzinfo=tzutc()), 'exponent': 0, 
'until': datetime.datetime(2019, 6, 14, 9, 9, 13, 924133,
 tzinfo=tzutc())} elastalert_error - {'message': "Uncaught exception running rule Low number of authentications: global name 'datetime' is not defined", 

 'traceback': 
   ['Traceback (most recent call last):', 
   ' File "elastalert/elastalert.py", line 1335, in alert', ' return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)', 
   ' File "elastalert/elastalert.py", line 1399, in send_alert', ' enhancement.process(match)', 
   ' File "elastalert_modules/my_enchancement.py", line 5, in process', ' if datetime.datetime.now().weekday() in [5, 6]:', 
   "NameError: global name 'datetime' is not defined"], 
   'data': 
   		{'rule': 'Low number of authentications'}} elastalert_status - 
   		{'hits': 0, 'matches': 2760, '@timestamp': datetime.datetime(2019, 6, 13, 9, 9, 14, 89361, tzinfo=tzutc()), 
   		'rule_name': 'Low number of authentications', 'starttime': datetime.datetime(2019, 6, 12, 9, 8, 55, 199144, tzinfo=tzutc()),
   		'endtime': datetime.datetime(2019, 6, 13, 9, 8, 55, 199144, tzinfo=tzutc()), 
   		'time_taken': 18.867187976837158

```
How can I solve it?

**Comment by ep4sh** [comment]
I forget to import ```datetime``` module
Seems it helps
