### ISSUE TITLE
Error: Cannot find module 'elasticsearch'

### ISSUE THREAD

**Issue by zhengm-hub** [bitsensor/elastalert#109]
@bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> sh ./scripts/start.sh

internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'elasticsearch'
Require stack:
- /opt/elastalert-server/src/common/elasticsearch_client.js
- /opt/elastalert-server/src/handlers/metadata/get.js
- /opt/elastalert-server/src/routes/routes.js
- /opt/elastalert-server/src/routes/route_setup.js
- /opt/elastalert-server/src/elastalert_server.js
- /opt/elastalert-server/src/index.js
- /opt/elastalert-server/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/opt/elastalert-server/src/common/elasticsearch_client.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at loader (/opt/elastalert-server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/opt/elastalert-server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)

**Comment by nsano-rururu** [comment]
bitsensorp/elastalert is no longer maintained.
