### ISSUE TITLE
Unable to run elastalert with Elasticsearch 7.2

### ISSUE THREAD

**Issue by rlakshmi190** [bitsensor/elastalert#110]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
 
"__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
  
exec code in run_globals
  File "/opt/elastalert/elastalert/test_rule.py", line 445, in <module>
  
main()
  File "/opt/elastalert/elastalert/test_rule.py", line 441, in main
   
test_instance.run_rule_test()
  File "/opt/elastalert/elastalert/test_rule.py", line 408, in run_rule_test
    
conf = load_conf(args, defaults, overwrites)
  File "elastalert/config.py", line 47, in load_conf
    
configure_logging(args, conf)
  File "elastalert/config.py", line 106, in configure_logging
    
if args.verbose and args.debug:
AttributeError
: 
'Namespace' object has no attribute 'verbose'

**Comment by rlakshmi190** [comment]
Can anyone please help with this.

**Comment by rlakshmi190** [comment]
fixed it

**Comment by btmndkh** [comment]
Please share how did you fix it?
