### ISSUE TITLE
Unable to trigger email by creating rule

### ISSUE THREAD

**Issue by Kuldeep6290** [bitsensor/elastalert#112]
I have elastalert:3.0.0-beta.0 installed using docker in windows
Following is my rule .yaml file

name: Example email rule
type: frequency
index: Winlogbeat-*
num_events: 2
timeframe:
  hours: 1
filter:
- term:
    winlog.channel: "Application"
alert:
- "email"
email:
- "elastalert@example.com"
from_addr: "kuldeep.patil@test.com"
smtp_host: "smtp.gmail.com"
smtp_port: 587
smtp_ssl: true
smtp_auth_file: "/opt/elastalert/rule_templates/smtp_auth_file.yaml"

I get error as 
11:15:25.627Z ERROR elastalert-server:
    ProcessController:  ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_config_change (trigger: interval[0:00:05], next run at: 2019-08-02 11:15:30 UTC)" raised an exception
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/APScheduler-3.6.0-py2.7.egg/apscheduler/executors/base.py", line 125, in run_job
        retval = job.func(*job.args, **job.kwargs)
      File "/opt/elastalert/elastalert/elastalert.py", line 1211, in handle_config_change
        self.load_rule_changes()
      File "/opt/elastalert/elastalert/elastalert.py", line 1094, in load_rule_changes
        new_rule = self.init_rule(new_rule, False)
      File "/opt/elastalert/elastalert/elastalert.py", line 957, in init_rule
        self.scheduler.remove_job(job_id=new_rule['name'])
      File "/usr/lib/python2.7/site-packages/APScheduler-3.6.0-py2.7.egg/apscheduler/schedulers/base.py", line 621, in remove_job
        raise JobLookupError(job_id)
    JobLookupError: u'No job by the id of Example email rule was found'

Please can anybody help...

**Comment by Kuldeep6290** [comment]
@martijnrondeel please could you look into this issue.
