### ISSUE TITLE
Elasticsearch connection fails - Status 401

### ISSUE THREAD

**Issue by SMAPPER** [bitsensor/elastalert#113]
Is there a way to get this to work when Elasticsearch requires authentication? I can get a standalone instance of ElastAlert to work using basic authentication but I cannot seem to get the bitsensor/elastalert Docker instance to work with it. I have the same basic authentication credentials and docker DNS name in that I successfully use within a separate test docker container.

Is it because there are no authentication specifications in config.json? Any help on this would be greatly appreciated.

**Comment by SMAPPER** [comment]
Here's output of container:

ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.804Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.804Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.805Z  INFO elastalert-server: ProcessController:  Setting ElastAlert verbose mode. This will increase the logging verboseness, which allows you to see information about the state of queries.
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.806Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments --verbose
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.824Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 47)
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.827Z  INFO elastalert-server: Server:  Server listening on port 3030
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.829Z  INFO elastalert-server: Server:  Websocket listening on port 3333
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:08.830Z  INFO elastalert-server: Server:  Server started
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.716Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  /usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/http_requests.py:92: UserWarning: Connecting to https://ha_client:9200 using SSL with verify_certs=False is insecure.
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       % self.base_url
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.734Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  /usr/lib/python2.7/site-packages/urllib3-1.24.3-py2.7.egg/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       InsecureRequestWarning)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.740Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  WARNING:elasticsearch:GET https://ha_client:9200/ [status:401 request:0.024s]
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.740Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  WARNING:elastalert:Error connecting to Elasticsearch for rule Password Spraying Windows. The rule has been disabled.
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.744Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  ERROR:root:Error connecting to SMTP host: [Errno 99] Address not available
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.765Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  /usr/lib/python2.7/site-packages/urllib3-1.24.3-py2.7.egg/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       InsecureRequestWarning)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.773Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  WARNING:elasticsearch:GET https://ha_client:9200/ [status:401 request:0.029s]
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.774Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  Traceback (most recent call last):
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.774Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      "__main__", fname, loader, pkg_name)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.774Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      exec code in run_globals
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.775Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      sys.exit(main(sys.argv[1:]))
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.775Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:    File "/opt/elastalert/elastalert/elastalert.py", line 1923, in main
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.776Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      client = ElastAlerter(args)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.777Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:    File "/opt/elastalert/elastalert/elastalert.py", line 141, in __init__
ha_elastalert.1.t0501fqjz0dd@cloud01a    |         if not self.init_rule(rule):
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/opt/elastalert/elastalert/elastalert.py", line 943, in init_rule
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.777Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      self.send_notification_email(exception=e, rule=new_rule)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.777Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:    File "/opt/elastalert/elastalert/elastalert.py", line 1856, in send_notification_email
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.778Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      self.handle_error('Error connecting to SMTP host: %s' % (e), {'email_body': email_body})
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/opt/elastalert/elastalert/elastalert.py", line 1807, in handle_error
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.779Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      self.writeback('elastalert_error', body)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/opt/elastalert/elastalert/elastalert.py", line 1477, in writeback
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.780Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      if(self.is_atleastsix()):
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/opt/elastalert/elastalert/elastalert.py", line 162, in is_atleastsix
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.780Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      return int(self.es_version.split(".")[0]) >= 6
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/opt/elastalert/elastalert/elastalert.py", line 155, in es_version
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.780Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      self._es_version = self.get_version()
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/opt/elastalert/elastalert/elastalert.py", line 149, in get_version
ha_elastalert.1.t0501fqjz0dd@cloud01a    |         info = self.writeback_es.info()
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.780Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      return func(*args, params=params, **kwargs)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/__init__.py", line 259, in info
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.780Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      return self.transport.perform_request("GET", "/", params=params)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/transport.py", line 353, in perform_request
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.781Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      timeout=timeout,
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 143, in perform_request
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.781Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:      self._raise_error(response.status_code, raw_data)
ha_elastalert.1.t0501fqjz0dd@cloud01a    |       File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/base.py", line 168, in _raise_error
ha_elastalert.1.t0501fqjz0dd@cloud01a    |         status_code, error_message, additional_info
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.781Z ERROR elastalert-server:
ha_elastalert.1.t0501fqjz0dd@cloud01a    |     ProcessController:  elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, {u'root_cause': [{u'reason': u'forbidden'}], u'reason': u'forbidden'}, u'forbidden')
ha_elastalert.1.t0501fqjz0dd@cloud01a    |
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.819Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.819Z  INFO elastalert-server: Server:  Stopping server
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.820Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
ha_elastalert.1.t0501fqjz0dd@cloud01a    | 18:38:09.820Z  INFO elastalert-server: Server:  Server stopped. Bye!

**Comment by SMAPPER** [comment]
Oddly enough, adding certificate verification fixed the issue. During testing, I disabled certificate verification. With it off it would not work. Once I enabled it things started working.
