### ISSUE TITLE
mapper parsing exception when triggering alert from journalbeat index

### ISSUE THREAD

**Issue by jmcclelland** [bitsensor/elastalert#125]
I'm working on a custom alert and when it triggers, I get the following backtrace. The trigger code does execute properly, so I suspect this backtrace happens when elastalert tries to write back the info to the elastalert_status index.

That index seems to expect the value of process.capabilities to be a long, but journalbeat passes a string.

Am I doing something wrong? I'm not sure if this is something I can configure? 

Thanks for any insight you can provide.

```
WARNING:elasticsearch:POST https://log-001.mayfirst.test:9200/elastalert_status/_doc [status:400 request:0.014s]
ERROR:root:Error writing alert info to Elasticsearch: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.process.capabilites] of type [long] in document with id 'MazvDm0BENOSXOXVf0mD'. Preview of field's value: 'a00425fb'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/elastalert-0.2.1-py3.7.egg/elastalert/elastalert.py", line 1599, in writeback
    res = self.writeback_es.index(index=index, body=body)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/connection/http_requests.py", line 156, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.7/dist-packages/elasticsearch-7.0.3-py3.7.egg/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', "failed to parse field [match_body.process.capabilites] of type [long] in document with id 'MazvDm0BENOSXOXVf0mD'. Preview of field's value: 'a00425fb'")
```

**Comment by jmcclelland** [comment]
Woops - meant to post to https://github.com/Yelp/elastalert!
