### ISSUE TITLE
Error starting ElastAlert docker container

### ISSUE THREAD

**Issue by ferezito** [bitsensor/elastalert#128]
Good afternoon. I am trying to tear out the image of the docker as it says in the official git: https://github.com/Yelp/elastalert
I have version 7.3.4 of elasticsearch, and when I get ready to start the ElastAlert Server container, after a few seconds it stops. Then I leave the logs of the container. Can you help me? Thank you.

`> @bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> sh ./scripts/start.sh

09:43:31.328Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
09:43:31.335Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
09:43:31.336Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
09:43:31.345Z  INFO elastalert-server: Router:  Listening for GET request on /.
09:43:31.345Z  INFO elastalert-server: Router:  Listening for GET request on /status.
09:43:31.345Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
09:43:31.346Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
09:43:31.346Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
09:43:31.348Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
09:43:31.349Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
09:43:31.349Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
09:43:31.349Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
09:43:31.349Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
09:43:31.350Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
09:43:31.350Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
09:43:31.350Z  INFO elastalert-server: Router:  Listening for POST request on /test.
09:43:31.350Z  INFO elastalert-server: Router:  Listening for GET request on /config.
09:43:31.350Z  INFO elastalert-server: Router:  Listening for POST request on /config.
09:43:31.351Z  INFO elastalert-server: Router:  Listening for POST request on /download.
09:43:31.351Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
09:43:31.351Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
09:43:31.351Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
09:43:31.356Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
09:43:31.356Z  INFO elastalert-server: ProcessController:  Creating index
09:43:35.421Z  INFO elastalert-server:
    ProcessController:  Elastic Version:7
    Mapping used for string:{'type': 'keyword'}

09:43:35.423Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/create_index.py", line 275, in <module>
        main()
      File "/opt/elastalert/elastalert/create_index.py", line 252, in main
        es.indices.put_mapping(index=index, doc_type='elastalert', body=es_mapping)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/indices.py", line 339, in put_mapping
        "PUT", _make_path(index, "_mapping", doc_type), params=params, body=body
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/transport.py", line 353, in perform_request
        timeout=timeout,
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 143, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/connection/base.py", line 168, in _raise_error
        status_code, error_message, additional_info
    elasticsearch.exceptions.RequestError: RequestError(400, u'illegal_argument_exception', u'Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.')

09:43:35.425Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
09:43:35.425Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
09:43:35.426Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
09:43:35.439Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 47)
09:43:35.441Z  INFO elastalert-server: Server:  Server listening on port 3030
09:43:35.443Z  INFO elastalert-server: Server:  Websocket listening on port 3333
09:43:35.443Z  INFO elastalert-server: Server:  Server started
09:43:36.442Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):

09:43:36.442Z ERROR elastalert-server:
    ProcessController:    File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>

09:43:36.444Z ERROR elastalert-server:
    ProcessController:      sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main

09:43:36.445Z ERROR elastalert-server:
    ProcessController:      client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start

09:43:36.446Z ERROR elastalert-server:
    ProcessController:      self.run_all_rules()
      File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules

09:43:36.447Z ERROR elastalert-server:
    ProcessController:      self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts

09:43:36.448Z ERROR elastalert-server:
    ProcessController:      pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts

09:43:36.449Z ERROR elastalert-server:
    ProcessController:      size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped

09:43:36.449Z ERROR elastalert-server:
    ProcessController:      return func(*args, params=params, **kwargs)
    TypeError: search() got an unexpected keyword argument 'doc_type'

09:43:36.485Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
09:43:36.486Z  INFO elastalert-server: Server:  Stopping server
09:43:36.486Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
09:43:36.486Z  INFO elastalert-server: Server:  Server stopped. Bye!
root@ElastAlert1:/opt/elastalert# 09:43:36.485Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
-bash: 09:43:36.485Z: no se encontró la orden
root@ElastAlert1:/opt/elastalert# ERROR elastalert-server: ProcessController:  Index create exited with code 1
`
Thanks.

**Comment by jusmitch** [comment]
Same issue here using a fresh Amazon Linux 2 vm.

**Comment by SolomonShorser-OICR** [comment]
I'm seeing the same error, with elasticsearch 6.6.0 and bitsensor/elastalert:2.0.1

**Comment by SlavikCA** [comment]
Is this issue duplicate to https://github.com/bitsensor/elastalert/issues/132 ?

**Comment by SolomonShorser-OICR** [comment]
Hmm... possibly?

**Comment by nsano-rururu** [comment]
@ferezito 

bitsensor/elastalert:2.0.1 and bitsensor/elastalert:latest are not compatible with Elasticsearch 7.x (includes ElastAlert v0.1.39)
Elasticsearch 7.x is compatible with bitsensor/elastalert:3.0.0-beta.0. (Includes ElastAlert v0.2.0b2. ElastAlert supports Elasticsearch 7.x from 0.2.0b2)
https://github.com/bitsensor/elastalert/tree/3.0.0-beta.0
