### ISSUE TITLE
Installing without Docker

### ISSUE THREAD

**Issue by KnutAtteslander** [bitsensor/elastalert#139]
Hello

I tried installing elastalert without docker.
yelp/elastalert: 0.2.1 (/opt/elastalert)
bitsensor/elastalert: 2.0.1 (/opt/elastalert-server)
Ubuntu 18.04

I replicated the steps from the Dockerfile, output `npm start`:
```
> @bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> sh ./scripts/start.sh

./scripts/start.sh: 3: ./scripts/start.sh: ./node_modules/.bin/bunyan: not found
module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/elastalert-server/index.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 4.15.0-66-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @bitsensor/elastalert@2.0.1 start: `sh ./scripts/start.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @bitsensor/elastalert@2.0.1 start script 'sh ./scripts/start.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @bitsensor/elastalert package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh ./scripts/start.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @bitsensor/elastalert
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @bitsensor/elastalert
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/elastalert-server/npm-debug.log
```
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @bitsensor/elastalert@2.0.1~prestart: @bitsensor/elastalert@2.0.1
6 silly lifecycle @bitsensor/elastalert@2.0.1~prestart: no script for prestart, continuing
7 info lifecycle @bitsensor/elastalert@2.0.1~start: @bitsensor/elastalert@2.0.1
8 verbose lifecycle @bitsensor/elastalert@2.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle @bitsensor/elastalert@2.0.1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/opt/elastalert-server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle @bitsensor/elastalert@2.0.1~start: CWD: /opt/elastalert-server
11 silly lifecycle @bitsensor/elastalert@2.0.1~start: Args: [ '-c', 'sh ./scripts/start.sh' ]
12 info lifecycle @bitsensor/elastalert@2.0.1~start: Failed to exec start script
13 verbose stack Error: @bitsensor/elastalert@2.0.1 start: `sh ./scripts/start.sh`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @bitsensor/elastalert@2.0.1
15 verbose cwd /opt/elastalert-server
16 error Linux 4.15.0-66-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "start"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error @bitsensor/elastalert@2.0.1 start: `sh ./scripts/start.sh`
24 error spawn ENOENT
25 error Failed at the @bitsensor/elastalert@2.0.1 start script 'sh ./scripts/start.sh'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the @bitsensor/elastalert package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     sh ./scripts/start.sh
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs @bitsensor/elastalert
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls @bitsensor/elastalert
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by nsano-rururu** [comment]
bitsensorp/elastalert is no longer maintained.
