### ISSUE TITLE
按照官网安装步骤不能安装成功，我的ELK是7.0版本

### ISSUE THREAD

**Issue by 739019118** [bitsensor/elastalert#142]
> @bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> sh ./scripts/start.sh

/opt/elastalert-server/src/common/websocket.js:34
  wss.clients.forEach(function (ws) {
      ^

TypeError: Cannot read property 'clients' of null
    at Timeout._onTimeout (/opt/elastalert-server/src/common/websocket.js:22:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
11:24:28.480Z  INFO elastalert-server: Server:  Stopping server

**Comment by nsano-rururu** [comment]
@739019118 

bitsensor / elastalert：2.0.1与Elasticsearch 7.x不兼容（包括ElastAlert v0.1.39）
Elasticsearch 7.x与bitsensor / elastalert：3.0.0-beta.0兼容。 （包括ElastAlertv0.2.0b2。ElastAlert从0.2.0b2开始支持Elasticsearch 7.x）
https://github.com/bitsensor/elastalert/tree/3.0.0-beta.0

**Comment by nsano-rururu** [comment]
bitsensorp/elastalert is no longer maintained.
