### ISSUE TITLE
unable to install the elastalert server via docker

### ISSUE THREAD

**Issue by shettypriy** [bitsensor/elastalert#166]
running the command gives me the following error.I am uaing es version 7.5.1. Somebody please help me

docker run -it -p 3030:3030 -p 3333:3333     -v `pwd`/config/elastalert.yaml:/opt/elastalert/config.yaml     -v `pwd`/config/elastalert-test.yaml:/opt/elastalert/config-test.yaml     -v `pwd`/config/config.json:/opt/elastalert-server/config/config.json     -v `pwd`/rules:/opt/elastalert/rules     -v `pwd`/rule_templates:/opt/elastalert/rule_templates     --net="host"     --name elastalert_new bitsensor/elastalert:latest
WARNING: Published ports are discarded when using host network mode

> @bitsensor/elastalert@2.0.1 start /opt/elastalert-server
> sh ./scripts/start.sh

20:48:07.958Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
20:48:07.959Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
20:48:07.960Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
20:48:07.964Z  INFO elastalert-server: Router:  Listening for GET request on /.
20:48:07.964Z  INFO elastalert-server: Router:  Listening for GET request on /status.
20:48:07.965Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
20:48:07.965Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
20:48:07.965Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
20:48:07.966Z  INFO elastalert-server: Router:  Listening for POST request on /test.
20:48:07.968Z  INFO elastalert-server: Router:  Listening for GET request on /config.
20:48:07.968Z  INFO elastalert-server: Router:  Listening for POST request on /config.
20:48:07.968Z  INFO elastalert-server: Router:  Listening for POST request on /download.
20:48:07.968Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
20:48:07.969Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
20:48:07.969Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
20:48:07.970Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
20:48:07.971Z  INFO elastalert-server: ProcessController:  Creating index
20:48:08.495Z  INFO elastalert-server:
    ProcessController:  Elastic Version:7
    Mapping used for string:{'type': 'keyword'}
    Index elastalert_status already exists. Skipping index creation.
    
20:48:08.495Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
20:48:08.495Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
20:48:08.499Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 47)
20:48:08.500Z  INFO elastalert-server: Server:  Server listening on port 3030
20:48:08.501Z  INFO elastalert-server: Server:  Websocket listening on port 3333
20:48:08.501Z  INFO elastalert-server: Server:  Server started
20:48:09.015Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    
20:48:09.015Z ERROR elastalert-server:
    ProcessController:      "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/elastalert.py", line 1929, in <module>
        sys.exit(main(sys.argv[1:]))
      File "/opt/elastalert/elastalert/elastalert.py", line 1925, in main
    
20:48:09.015Z ERROR elastalert-server:
    ProcessController:      client.start()
      File "/opt/elastalert/elastalert/elastalert.py", line 1106, in start
    
20:48:09.016Z ERROR elastalert-server:
    ProcessController:      self.run_all_rules()
      File "/opt/elastalert/elastalert/elastalert.py", line 1158, in run_all_rules
    
20:48:09.016Z ERROR elastalert-server:
    ProcessController:      self.send_pending_alerts()
      File "/opt/elastalert/elastalert/elastalert.py", line 1534, in send_pending_alerts
    
20:48:09.016Z ERROR elastalert-server:
    ProcessController:      pending_alerts = self.find_recent_pending_alerts(self.alert_time_limit)
      File "/opt/elastalert/elastalert/elastalert.py", line 1526, in find_recent_pending_alerts
    
20:48:09.016Z ERROR elastalert-server:
    ProcessController:      size=1000)
      File "/usr/lib/python2.7/site-packages/elasticsearch-7.0.1-py2.7.egg/elasticsearch/client/utils.py", line 84, in _wrapped
        return func(*args, params=params, **kwargs)
    TypeError
20:48:09.017Z ERROR elastalert-server:
    ProcessController:  : search() got an unexpected keyword argument 'doc_type'
    
20:48:09.033Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
20:48:09.034Z  INFO elastalert-server: Server:  Stopping server
20:48:09.034Z  INFO elastalert-server: ProcessController:  ElastAlert is not running
20:48:09.034Z  INFO elastalert-server: Server:  Server stopped. Bye!

**Comment by daichi703n** [comment]
@shettypriy duplicate with https://github.com/bitsensor/elastalert/issues/150 ?

**Comment by nsano-rururu** [comment]
@shettypriy 

ElastAlert Server Docker Images

| Docker image name    | tag| ElastAlert |Elasticsearch 7 Support|   Remarks    |
|:-------------------|:----:|:----------:|:----------:|:-----------|
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|2.0.1 |0.1.39|×||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|lastet|0.1.39|×||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|3.0.0-beta.0|0.2.0b2|〇||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|3.0.0-beta.1|0.2.0b2|〇||
|[servercentral/elastalert](https://hub.docker.com/r/servercentral/elastalert)|latest|0.2.1|〇|bitsensor/elastalert fork<br>Customize<br>bugfix<br>Python 3.6|
|[daichi703n/elastalert](https://hub.docker.com/r/daichi703n/elastalert)|0.2.1-dev2|0.2.1|〇|servercentral/elastalert fork<br>Customize<br>bugfix<br>Python 3.6|
|[praecoapp/elastalert-server](https://hub.docker.com/r/praecoapp/elastalert-server)|latest|0.2.4|〇|servercentral/elastalert fork<br>Customize<br>bugfix<br>Library Update<br>Python 3.8|
