### ISSUE TITLE
Unable to start elastalert after updating joi to 13.1.2

### ISSUE THREAD

**Issue by gips0n** [bitsensor/elastalert#20]
[Building from source](https://github.com/bitsensor/elastalert#building-from-source) currently is broken, I'm receiving next error:
```
$ npm start

> @bitsensor/elastalert@0.0.9 start /opt/elastalert
> sh ./scripts/start.sh

/opt/elastalert/node_modules/joi/lib/index.js:48
    root.any = function (...args) {
                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/elastalert/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/elastalert/src/common/config/server_config.js:1:1)
    at Module._compile (module.js:409:26)
```

In this commit https://github.com/bitsensor/elastalert/commit/cee3014fd75102a273d1d4b0e55850ed9d932693 joi was updated to 13.1.2, but according to https://github.com/hapijs/joi/blob/master/package.json v.13.1.2 requires "node": ">=8.9.0" and https://github.com/bitsensor/elastalert/blob/develop/.node-version 4.5.0 is not sufficient

**Comment by martijnrondeel** [comment]
The `.node-version` has been replaced with a `.nvmrc` file now which has the right Node version needed to build the project.
