### ISSUE TITLE
Elastalert is throwing Syntax error while testing alert 

### ISSUE THREAD

**Issue by abhispandey12** [bitsensor/elastalert#207]
Hi,
When I am trying to test my elastalert rule, its throwing **SyntaxError: invalid syntax**. Below are the error I'm getting 

`Traceback (most recent call last):
  File "/usr/local/bin/elastalert-test-rule", line 33, in <module>
    sys.exit(load_entry_point('elastalert==0.2.0b2', 'console_scripts', 'elastalert-test-rule')())
  File "/usr/local/bin/elastalert-test-rule", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/elastalert/test_rule.py", line 15, in <module>
    from elastalert.config import load_conf
  File "/usr/local/lib/python3.5/dist-packages/elastalert/config.py", line 8, in <module>
    from elastalert import loaders
  File "/usr/local/lib/python3.5/dist-packages/elastalert/loaders.py", line 33, in <module>
    import elastalert.alerters.thehive
  File "/usr/local/lib/python3.5/dist-packages/elastalert/alerters/thehive.py", line 113
    req = f'{hive_host}:{hive_port}/api/alert'
                                             ^
SyntaxError: invalid syntax
`
Can any one please help me on this

**Comment by nsano-rururu** [comment]
https://github.com/Karql/elastalert2-server
