### ISSUE TITLE
400 error with elasticsearch 6.2.3/6.2.4

### ISSUE THREAD

**Issue by ccao93** [bitsensor/elastalert#31]
I kept getting 400 errors while using elasticsearch v6.2.3 or v6.2.4. The detailed errors I got is like the following:
```

**Comment by Jimhox** [comment]
@ccao93  Can you please paste here the request you are doing?

**Comment by ccao93** [comment]
May I ask how to check the request I am doing? 
This is what I got by running `docker logs -f elastalert`
```elasticsearch:GET http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.003s]```

The rule used for it works properly for normal elastalert, but when I moved it to docker instance it will generate 400 errors.

**Comment by vitassecuriti** [comment]
Did you create the index for elastalert Manually before start of ElastAlert?

python elastalert/elastalert/create_index.py --config /somepath/elastalert_conf.yaml

**Comment by ccao93** [comment]
Yes, I did, and the index name is the same as what I set up for Docker server.

**Comment by sprabhuanand** [comment]
+1 I have the same issue

**Comment by sprabhuanand** [comment]
I started the docker container and it created the index and when it tried to run a rule, it failed with the error above.

**Comment by sprabhuanand** [comment]
Here is my log


05:41:25.203Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
05:41:25.205Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
05:41:25.206Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
05:41:25.216Z  INFO elastalert-server: Router:  Listening for GET request on /.
05:41:25.216Z  INFO elastalert-server: Router:  Listening for GET request on /status.
05:41:25.216Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
05:41:25.217Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
05:41:25.217Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
05:41:25.219Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
05:41:25.219Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
05:41:25.219Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
05:41:25.219Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
05:41:25.219Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
05:41:25.219Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
05:41:25.220Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
05:41:25.220Z  INFO elastalert-server: Router:  Listening for POST request on /test.
05:41:25.220Z  INFO elastalert-server: Router:  Listening for GET request on /config.
05:41:25.220Z  INFO elastalert-server: Router:  Listening for POST request on /config.
05:41:25.220Z  INFO elastalert-server: Router:  Listening for POST request on /download.
05:41:25.225Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
05:41:25.225Z  INFO elastalert-server: ProcessController:  Creating index
05:41:27.887Z ERROR elastalert-server:
    ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/create_index.py", line 169, in <module>
        main()
      File "/opt/elastalert/elastalert/create_index.py", line 153, in main
        es.indices.put_mapping(index=index, doc_type='elastalert', body=es_mapping)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py", line 282, in put_mapping
      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
    elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'No handler for type [string] declared on field [aggregate_id]')

05:41:27.888Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
05:41:27.888Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
05:41:27.889Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
05:41:27.895Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 47)
05:41:27.897Z  INFO elastalert-server: Server:  Server listening on port 3030
05:41:27.898Z  INFO elastalert-server: Server:  Server started
05:41:38.485Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.034s]

05:41:38.486Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:38.369414Z', 'from': '2018-06-26T05:41:38.369392Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
        size=1000)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
        return func(*args, params=params, **kwargs)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search
        doc_type, '_search'), params=params, body=body)
      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')

05:41:43.416Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.040s]

05:41:43.416Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:43.375391Z', 'from': '2018-06-26T05:41:43.375359Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
        size=1000)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
        return func(*args, params=params, **kwargs)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search
        doc_type, '_search'), params=params, body=body)
      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')

05:41:48.418Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.035s]

05:41:48.418Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:48.381851Z', 'from': '2018-06-26T05:41:48.381784Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
        size=1000)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
        return func(*args, params=params, **kwargs)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search
        doc_type, '_search'), params=params, body=body)
      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')

05:41:53.422Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.035s]

05:41:53.422Z ERROR elastalert-server:
    ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:53.387150Z', 'from': '2018-06-26T05:41:53.387048Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
    Traceback (most recent call last):
      File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
        size=1000)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
        return func(*args, params=params, **kwargs)
      File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search
        doc_type, '_search'), params=params, body=body)
      File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
        self._raise_error(response.status_code, raw_data)
      File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')

**Comment by vitassecuriti** [comment]
1. Paint steps. what are you doing completely.
2. Provide elastalert config
3. Provide your rule
4. What image do you use?


>Четверг, 28 июня 2018, 8:43 +03:00 от Prabhuanand Sivashanmugam <notifications@github.com>:
>
>Here is my log
>05:41:25.203Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
>05:41:25.205Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
>05:41:25.206Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
>05:41:25.216Z  INFO elastalert-server: Router:  Listening for GET request on /.
>05:41:25.216Z  INFO elastalert-server: Router:  Listening for GET request on /status.
>05:41:25.216Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
>05:41:25.217Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
>05:41:25.217Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
>05:41:25.219Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
>05:41:25.219Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
>05:41:25.219Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
>05:41:25.219Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
>05:41:25.219Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
>05:41:25.219Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
>05:41:25.220Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
>05:41:25.220Z  INFO elastalert-server: Router:  Listening for POST request on /test.
>05:41:25.220Z  INFO elastalert-server: Router:  Listening for GET request on /config.
>05:41:25.220Z  INFO elastalert-server: Router:  Listening for POST request on /config.
>05:41:25.220Z  INFO elastalert-server: Router:  Listening for POST request on /download.
>05:41:25.225Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
>05:41:25.225Z  INFO elastalert-server: ProcessController:  Creating index
>05:41:27.887Z ERROR elastalert-server:
>ProcessController:  Traceback (most recent call last):
>File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>" main ", fname, loader, pkg_name)
>File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>exec code in run_globals
>File "/opt/elastalert/elastalert/create_index.py", line 169, in 
>main()
>File "/opt/elastalert/elastalert/create_index.py", line 153, in main
>es.indices.put_mapping(index=index, doc_type='elastalert', body=es_mapping)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/indices.py", line 282, in put_mapping
>File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
>elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception', u'No handler for type [string] declared on field [aggregate_id]')
>05:41:27.888Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
>05:41:27.888Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
>05:41:27.889Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
>05:41:27.895Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 47)
>05:41:27.897Z  INFO elastalert-server: Server:  Server listening on port 3030
>05:41:27.898Z  INFO elastalert-server: Server:  Server started
>05:41:38.485Z ERROR elastalert-server:
>ProcessController:  WARNING:elasticsearch:GET  http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.034s]
>05:41:38.486Z ERROR elastalert-server:
>ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:38.369414Z', 'from': '2018-06-26T05:41:38.369392Z'}}}, 'query': {'query_string': {'query': '! exists :aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
>Traceback (most recent call last):
>File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
>size=1000)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
>return func(*args, params=params, **kwargs)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/ init .py", line 623, in search
>doc_type, '_search'), params=params, body=body)
>File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
>status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
>self._raise_error(response.status_code, raw_data)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
>raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
>RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
>05:41:43.416Z ERROR elastalert-server:
>ProcessController:  WARNING:elasticsearch:GET  http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.040s]
>05:41:43.416Z ERROR elastalert-server:
>ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:43.375391Z', 'from': '2018-06-26T05:41:43.375359Z'}}}, 'query': {'query_string': {'query': '! exists :aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
>Traceback (most recent call last):
>File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
>size=1000)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
>return func(*args, params=params, **kwargs)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/ init .py", line 623, in search
>doc_type, '_search'), params=params, body=body)
>File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
>status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
>self._raise_error(response.status_code, raw_data)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
>raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
>RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
>05:41:48.418Z ERROR elastalert-server:
>ProcessController:  WARNING:elasticsearch:GET  http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.035s]
>05:41:48.418Z ERROR elastalert-server:
>ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:48.381851Z', 'from': '2018-06-26T05:41:48.381784Z'}}}, 'query': {'query_string': {'query': '! exists :aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
>Traceback (most recent call last):
>File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
>size=1000)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
>return func(*args, params=params, **kwargs)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/ init .py", line 623, in search
>doc_type, '_search'), params=params, body=body)
>File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
>status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
>self._raise_error(response.status_code, raw_data)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
>raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
>RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
>05:41:53.422Z ERROR elastalert-server:
>ProcessController:  WARNING:elasticsearch:GET  http://localhost:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.035s]
>05:41:53.422Z ERROR elastalert-server:
>ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-06-28T05:41:53.387150Z', 'from': '2018-06-26T05:41:53.387048Z'}}}, 'query': {'query_string': {'query': '! exists :aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
>Traceback (most recent call last):
>File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
>size=1000)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
>return func(*args, params=params, **kwargs)
>File "build/bdist.linux-x86_64/egg/elasticsearch/client/ init .py", line 623, in search
>doc_type, '_search'), params=params, body=body)
>File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
>status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
>self._raise_error(response.status_code, raw_data)
>File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
>raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
>RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением!!! Виталий.

**Comment by sprabhuanand** [comment]
**what are you doing completely** 
Am trying to run a rule against the elasticsearch

**Provide elastalert config**
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: localhost

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 5

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

**Provide your rule**
None

**What image do you use?**
bitsensor/elastalert:latest

**Comment by HitsuYaga** [comment]
I have the same error:
Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Error running query: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')", 'traceback': ['Traceback (most recent call last):', '  File "elastalert/elastalert.py", line 369, in get_hits', '    **extra_args', '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search', "    doc_type, '_search'), params=params, body=body)", '  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'parsing_exception', u'no [query] registered for [filtered]')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'filtered': {'filter': {'bool': {'must': [{'range': {'@timestamp': {'gt': '2018-06-30T10:50:19.835712Z', 'lte': '2018-06-30T10:55:19.835712Z'}}}, {'term': {'clientip': '8.8.8.8'}}]}}}}}, 'rule': 'Apache Rules'}}

ELK version: 6.2.3
ElasAlert server installation using docker with latest image

**Comment by AlbertasG** [comment]
Same issue with response code 400 from docker container
Trying to run 'curl' from container manually gives correct response body with status code 200

Latest Docker Image and 6.2.3 Kibana

ProcessController:  WARNING:elasticsearch:GET http://elasticsearch:9200/elastalert_status/elastalert/_search?size=1000 [status:400 request:0.003s]
--
  |  
  | 09:00:05.023Z ERROR elastalert-server:
  | ProcessController:  ERROR:root:Error finding recent pending alerts: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].') {'filter': {'range': {'alert_time': {'to': '2018-07-03T09:00:05.019924Z', 'from': '2018-07-01T09:00:05.019889Z'}}}, 'query': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'sort': {'alert_time': {'order': 'asc'}}}
  | Traceback (most recent call last):
  | File "/opt/elastalert/elastalert/elastalert.py", line 1411, in find_recent_pending_alerts
  | size=1000)
  | File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped
  | return func(*args, params=params, **kwargs)
  | File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search
  | doc_type, '_search'), params=params, body=body)
  | File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request
  | status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  | File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request
  | self._raise_error(response.status_code, raw_data)
  | File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error
  | raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
  | RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')
`

**Comment by martijnrondeel** [comment]
This is probably solved with https://github.com/bitsensor/elastalert/commit/e544da27847486d437286e3cf106d5ff98e26276. Let me know if using the latest docker image fixed your issues.
