### ISSUE TITLE
Starting server failed with error: TypeError: object must be passed

### ISSUE THREAD

**Issue by japel** [bitsensor/elastalert#55]
I believe there is a problem when loading the configuration. When I run elastalert I'm getting the following messages:
```bash
elastalert_1     | 16:29:20.932Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
elastalert_1     | 16:29:20.998Z ERROR elastalert-server:
elastalert_1     |     Server:  Starting server failed with error: TypeError: object must be passed
elastalert_1     |         at module.exports (/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13:11)
elastalert_1     |         at ServerConfig.get (/opt/elastalert-server/src/common/config/server_config.js:33:12)
elastalert_1     |         at /opt/elastalert-server/src/elastalert_server.js:66:58
elastalert_1     |         at /opt/elastalert-server/src/common/config/server_config.js:61:9
elastalert_1     |         at Array.forEach (<anonymous>)
elastalert_1     |         at /opt/elastalert-server/src/common/config/server_config.js:60:22
elastalert_1     | 16:29:21.002Z  INFO elastalert-server: Server:  Stopping server
elastalert_1     | 16:29:21.015Z  INFO elastalert-server: Server:  Stopping server
elastalert_1     | /opt/elastalert-server/src/elastalert_server.js:124
elastalert_1     |       this._processController.stop();
elastalert_1     |                               ^
elastalert_1     |
elastalert_1     | TypeError: Cannot read property 'stop' of null
elastalert_1     |     at ElastalertServer.stop (/opt/elastalert-server/src/elastalert_server.js:90:29)
elastalert_1     |     at process.<anonymous> (/opt/elastalert-server/src/elastalert_server.js:31:12)
elastalert_1     |     at process.emit (events.js:182:13)
```
I first thought it might be a volume mounting issue, as I saw other issues with a similar error, so I checked this by console.logging `this._jsonConfig` in `common/config/server_config.js:33`
The output was correct:
```bash
elastalert_1     | {
elastalert_1     |   "appName": "elastalert-server",
elastalert_1     |   "port": 3030,
elastalert_1     |   "elastalertPath": "/opt/elastalert",
elastalert_1     |   "verbose": true,
elastalert_1     |   "es_debug": true,
elastalert_1     |   "debug": false,
elastalert_1     |   "rulesPath": {
elastalert_1     |     "relative": true,
elastalert_1     |     "path": "/rules"
elastalert_1     |   },
elastalert_1     |   "templatesPath": {
elastalert_1     |     "relative": true,
elastalert_1     |     "path": "/rule_templates"
elastalert_1     |   },
elastalert_1     |   "dataPath": {
elastalert_1     |     "relative": true,
elastalert_1     |     "path": "/server_data"
elastalert_1     |   },
elastalert_1     |   "es_host": "elasticsearch", // For getting metadata and field mappings, connect to this ES server
elastalert_1     |   "es_port": 9200, // Port for above
elastalert_1     |   "writeback_index": "elastalert_status" // Writeback index to examine for /metadata endpoint
elastalert_1     | }
elastalert_1     | 16:37:28.843Z ERROR elastalert-server:
elastalert_1     |     Server:  Starting server failed with error: TypeError: object must be passed
elastalert_1     |         at module.exports (/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13:11)
elastalert_1     |         at ServerConfig.get (/opt/elastalert-server/src/common/config/server_config.js:33:12)
elastalert_1     |         at /opt/elastalert-server/src/elastalert_server.js:66:58
elastalert_1     |         at /opt/elastalert-server/src/common/config/server_config.js:61:9
elastalert_1     |         at Array.forEach (<anonymous>)
elastalert_1     |         at /opt/elastalert-server/src/common/config/server_config.js:60:22
elastalert_1     | 16:37:28.843Z  INFO elastalert-server: Server:  Stopping server
elastalert_1     | 16:37:28.846Z  INFO elastalert-server: Server:  Stopping server
elastalert_1     | /opt/elastalert-server/src/elastalert_server.js:124
elastalert_1     |       this._processController.stop();
elastalert_1     |                               ^
elastalert_1     |
elastalert_1     | TypeError: Cannot read property 'stop' of null
elastalert_1     |     at ElastalertServer.stop (/opt/elastalert-server/src/elastalert_server.js:90:29)
elastalert_1     |     at process.<anonymous> (/opt/elastalert-server/src/elastalert_server.js:31:12)
elastalert_1     |     at process.emit (events.js:182:13)
```

Then I took a look at `/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13`
which expects an `object`, so I console logged `typeof this._jsonConfig` which outputted `string`:
```bash
elastalert_1     | 16:40:00.095Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
elastalert_1     | /opt/elastalert-server/src/elastalert_server.js:124
elastalert_1     |       this._processController.stop();
elastalert_1     |                               ^
elastalert_1     |
elastalert_1     | TypeError: Cannot read property 'stop' of null
elastalert_1     |     at ElastalertServer.stop (/opt/elastalert-server/src/elastalert_server.js:90:29)
elastalert_1     |     at process.<anonymous> (/opt/elastalert-server/src/elastalert_server.js:31:12)
elastalert_1     |     at process.emit (events.js:182:13)
elastalert_1     | 16:40:00.096Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
elastalert_1     | 16:40:00.096Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for POST request on /test.
elastalert_1     | 16:40:00.099Z  INFO elastalert-server: Router:  Listening for GET request on /config.
elastalert_1     | 16:40:00.100Z  INFO elastalert-server: Router:  Listening for POST request on /config.
elastalert_1     | 16:40:00.100Z  INFO elastalert-server: Router:  Listening for POST request on /download.
elastalert_1     | 16:40:00.100Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
elastalert_1     | 16:40:00.100Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
elastalert_1     | string
elastalert_1     | 16:40:00.120Z ERROR elastalert-server:
elastalert_1     |     Server:  Starting server failed with error: TypeError: object must be passed
elastalert_1     |         at module.exports (/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13:11)
elastalert_1     |         at ServerConfig.get (/opt/elastalert-server/src/common/config/server_config.js:33:12)
elastalert_1     |         at /opt/elastalert-server/src/elastalert_server.js:66:58
elastalert_1     |         at /opt/elastalert-server/src/common/config/server_config.js:61:9
elastalert_1     |         at Array.forEach (<anonymous>)
elastalert_1     |         at /opt/elastalert-server/src/common/config/server_config.js:60:22
elastalert_1     | 16:40:00.121Z  INFO elastalert-server: Server:  Stopping server
elastalert_1     | 16:40:00.123Z  INFO elastalert-server: Server:  Stopping server
```

My question is now, why my config is a `string` and not an `object`?

**Comment by japel** [comment]
I'm closing this, as I am just stupid and did not remove the comments from the config.json :shit:

**Comment by envy7** [comment]
@japel im facing the same issue, how did you resolve it? I don't see any comments in my config.json
