### ISSUE TITLE
Timeout or retries for creating index when elasticsearch is not ready yet?

### ISSUE THREAD

**Issue by mgranq** [bitsensor/elastalert#60]
Hi,

I use the bitsensor image:
bitsensor/elastalert:0.0.14

I have several containers running with docker stack.
When I deploy the stack the elasticsearch service is not always ready before elastalert tries to create the index.

So I get this error:
```sh
$ docker service logs elastalert5_elastalert                                                                                                  
@bitsensor/elastalert@0.0.14 start /opt/elastalert-server
sh ./scripts/start.sh
 
17:57:57.047Z  INFO elastalert-server: Config:  No config.dev.json file was found in /opt/elastalert-server/config/config.dev.json.
17:57:57.050Z  INFO elastalert-server: Config:  Proceeding to look for normal config file.
17:57:57.050Z  INFO elastalert-server: Config:  A config file was found in /opt/elastalert-server/config/config.json. Using that config.
17:57:57.071Z  INFO elastalert-server: Router:  Listening for GET request on /.
17:57:57.071Z  INFO elastalert-server: Router:  Listening for GET request on /status.
17:57:57.071Z  INFO elastalert-server: Router:  Listening for GET request on /status/control/:action.
17:57:57.071Z  INFO elastalert-server: Router:  Listening for GET request on /status/errors.
17:57:57.071Z  INFO elastalert-server: Router:  Listening for GET request on /rules.
17:57:57.073Z  INFO elastalert-server: Router:  Listening for GET request on /rules/:id.
17:57:57.073Z  INFO elastalert-server: Router:  Listening for POST request on /rules/:id.
17:57:57.073Z  INFO elastalert-server: Router:  Listening for DELETE request on /rules/:id.
17:57:57.073Z  INFO elastalert-server: Router:  Listening for GET request on /templates.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for GET request on /templates/:id.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for POST request on /templates/:id.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for DELETE request on /templates/:id.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for POST request on /test.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for GET request on /config.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for POST request on /config.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for POST request on /download.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for GET request on /metadata/:type.
17:57:57.074Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
17:57:57.079Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
17:57:57.079Z  INFO elastalert-server: ProcessController:  Creating index
17:58:09.648Z ERROR elastalert-server:
ProcessController:  Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
 "__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
  exec code in run_globals
  File "/opt/elastalert/elastalert/create_index.py", line 277, in <module>
   main()
     File "/opt/elastalert/elastalert/create_index.py", line 129, in main
     esversion = es.info()["version"]["number"]
   File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/utils.py", line 76, in _wrapped
     return func(*args, params=params, **kwargs)
    File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/__init__.py", line 241, in info
     return self.transport.perform_request('GET', '/', params=params)
   File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request
      status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
    File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 85, in perform_reques
t
       raise ConnectionError('N/A', str(e), e)
  elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='elasticsearch', port=9200): Max retries exceeded with url:
 / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa32ea21190>: Failed to establish a new connection: [Errno 111] Connection refused',))) caused by: ConnectionError(HTTPCon
nectionPool(host='elasticsearch', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa32ea21190>: Failed to establish a new connec
tion: [Errno 111] Connection refused',)))
  
17:58:09.648Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
17:58:09.648Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
17:58:09.649Z  INFO elastalert-server: ProcessController:  Setting ElastAlert query beginning to time 2018-10-31T00:00:00
```

Is there any setting that i can use so that elastalert retries if the create index fails the first time.
I have tried setting the es_conn_timeout in both the config.json and elastalert.yaml but the create index still just try once and it doesn't seem like the timeout setting bites.

```json
...
  "es_host": "elasticsearch",
  "es_conn_timeout": 120,
  "es_port": 9200,
...
```
```yaml
...
es_host: elasticsearch
es_conn_timeout: 120
...
```

So not sure if the setting is not propagated to elastalert correctly.
Is there some other way to achieve what I need?

**Comment by martijnrondeel** [comment]
In version [2.0.0](https://github.com/bitsensor/elastalert/releases/tag/2.0.0) the program will exit when it cannot connect to ElasticSearch. I'd recommend using a Docker restart policy to try and start ElastAlert and connect to ES again.
