### ISSUE TITLE
ERROR elastalert-server

### ISSUE THREAD

**Issue by qakart** [bitsensor/elastalert#77]
ProcessController:  Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/opt/elastalert/elastalert/create_index.py", line 277, in <module>
        main()
      File "/opt/elastalert/elastalert/create_index.py", line 129, in main
        esversion = es.info()["version"]["number"]
      File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/utils.py", line 76, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/__init__.py", line 241, in info
        return self.transport.perform_request('GET', '/', params=params)
      File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request
        status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
      File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 85, in perform_request
        raise ConnectionError('N/A', str(e), e)
    elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdaa62c410>: Failed to establish a new connection: [Errno 111] Connection refused',))) caused by: ConnectionError(HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efdaa62c410>: Failed to establish a new connection: [Errno 111] Connection refused',)))
    
09:31:50.222Z ERROR elastalert-server: ProcessController:  Index create exited with code 1
09:31:50.222Z  WARN elastalert-server: ProcessController:  ElastAlert will start but might not be able to save its data!
09:31:50.222Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
09:31:50.228Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 49)
09:31:50.230Z  INFO elastalert-server: Server:  Server listening on port 3030
09:31:50.230Z  INFO elastalert-server: Server:  Server started
09:31:50.689Z ERROR elastalert-server:
    ProcessController:  WARNING:elasticsearch:GET http://localhost:80/ [status:N/A request:0.002s]
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 76, in perform_request
        response = self.session.send(prepared_request, **send_kwargs)
      File "/usr/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf366fcc10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by qakart** [comment]
as i am using EC2 docker 

i did curl from the elasticalert box to elasticsearch

`{
  "name" : "y14R2yj",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "BGFgXVZQTxeE58AvCEyvww",
  "version" : {
    "number" : "6.6.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "1fd8f69",
    "build_date" : "2019-02-13T17:10:04.160291Z",
    "build_snapshot" : false,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}`

**Comment by qakart** [comment]
Please let me know if you need any more details 
Thanks in Advance

**Comment by qakart** [comment]
issue fixed redeploy with fresh data and config
