### ISSUE TITLE
@Timestamp issue

### ISSUE THREAD

**Issue by qakart** [bitsensor/elastalert#78]
Console output
Successfully loaded Example frequency rule Would have written the following documents to writeback index (default is elastalert_status): elastalert_error - {'message': "Error running query: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')", 'traceback': ['Traceback (most recent call last):', ' File "elastalert/elastalert.py", line 370, in get_hits', ' **extra_args', ' File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/utils.py", line 76, in wrapped', ' return func(*args, params=params, **kwargs)', ' File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/client/init_.py", line 660, in search', " doc_type, '_search'), params=params, body=body)", ' File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/transport.py", line 318, in perform_request', ' status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)', ' File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/http_requests.py", line 90, in perform_request', ' self._raise_error(response.status_code, raw_data)', ' File "/usr/lib/python2.7/site-packages/elasticsearch-6.3.1-py2.7.egg/elasticsearch/connection/base.py", line 125, in _raise_error', ' raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')"], 'data': {'query': {'sort': [{'@timestamp': {'order': 'asc'}}], 'query': {'bool': {'filter': {'bool': {'must': [{'range': {'@timestamp':

{'gt': '2019-03-28T10:40:14.178693Z', 'lte': '2019-03-28T10:41:14.178693Z'}
}}, {'term': {'scenario_status': 'failed'}}]}}}}}, 'rule': 'Example frequency rule'}}

**Comment by qakart** [comment]
i am trying to find the custom time filed

**Comment by qakart** [comment]
its simple just found it use your own timefiled like below
timestamp_field : createdAt
